feat: Updated template

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -8,10 +8,13 @@
 # The goal of this workflow is to merge the remote branch into the Epitech remote, but only if the tests pass.
 
 name: "Push to remote"
-on:
-  push:
-    branches:
-      - '*'
+on: push
+
+# Set your variables here
+env:
+  MIRROR_URL: ""
+  EXECUTABLES: ""
+  DEPENDENCIES: ""
 
 jobs:
   test:
@@ -25,13 +28,62 @@ jobs:
         id: extract_branch
 
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v3
         with:
           ref: ${{ steps.extract_branch.outputs.branch }}
           fetch-depth: 0
 
-      - name: Run push hooks
-        run: "pip install websocket-client && python '__CHECKER_SCRIPT__' --hard"
+      # Note: remove this if you do not use criterion
+      - name: Install criterion
+        run: |
+            URL="https://github.com/Snaipe/Criterion/releases/download/v2.3.2"
+            TARBALL="criterion-v2.3.2-linux-x86_64.tar.bz2"
+            DIR="criterion-v2.3.2"
+            DST="/usr/local/"
+            SUDO=/usr/bin/sudo
+
+            if [ $UID -eq "0" ]; then
+              SUDO=""
+              echo "[no sudo for root]"
+            fi
+
+            cd /tmp
+            rm -f $TARBALL
+            rm -fr $DIR
+
+            wget $URL/$TARBALL
+            if [ $? != 0 ]; then
+              echo "failled, exiting"
+              exit 1;
+            fi
+
+            echo
+            echo "untaring $TARBALL"
+            tar xjf $TARBALL
+            if [ $? != 0 ]; then
+              echo "failled, exiting"
+              exit 1;
+            fi
+
+            echo "creating custom ld.conf"
+            $SUDO sh -c "echo "/usr/local/lib" > /etc/ld.so.conf.d/criterion.conf"
+            echo "cp headers to $DST/include..."
+            $SUDO cp -r $DIR/include/* $DST/include/
+            echo "cp lib to $DST/include..."
+            $SUDO cp -r $DIR/lib/* $DST/lib/
+            echo "run ldconfig."
+            $SUDO ldconfig
+            echo "all good."
+
+      # Note: remove this for a c++ project
+      - name: Check coding style
+        run: "pip install websocket-client && python ./.github/c_checker.py --hard"
+
+      - name: Install dependencies
+        shell: bash
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y ${{ env.DEPENDENCIES }}
 
       - name: Check if it compiles
         shell: bash
@@ -40,54 +92,15 @@ jobs:
           make clean
           make fclean
           make re
-          [ "$(make)" == "make: Nothing to be done for 'all'." ]
+          ls ${{ env.EXECUTABLES }}
 
       - name: Run tests (functional and unit)
         run: "make tests_run"
 
-  deploy:
-    name: Deploy to Epitech repo
-    runs-on: ubuntu-latest
-    needs: test
-    steps:
-      - name: Extract branch name
-        shell: bash
-        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
-        id: extract_branch
-
-      - name: Checkout
-        uses: actions/checkout@v2
-        with:
-          ref: ${{ steps.extract_branch.outputs.branch }}
-          fetch-depth: 0
-
-      - name: Configure SSH
-        run: |
-          mkdir -p ~/.ssh/
-          echo "$SSH_KEY" > ~/.ssh/staging.key
-          chmod 600 ~/.ssh/staging.key
-          cat >>~/.ssh/config <<END
-          Host staging
-            HostName $SSH_HOST
-            User $SSH_USER
-            IdentityFile ~/.ssh/staging.key
-            StrictHostKeyChecking no
-          END
-
-        env:
-          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
-          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
-          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
-
       - name: Push to Epitech
-        shell: bash
-        run: |
-          DIRNAME=githubActions/$(basename $GITHUB_REPOSITORY)
-          BRANCH=${{ steps.extract_branch.outputs.branch }}
-          ssh staging "rm -rf $DIRNAME && cd githubActions && git clone 'git@github.com:$GITHUB_REPOSITORY.git'"
-          ssh staging "cd $DIRNAME && git checkout $BRANCH && git pull"
-          ssh staging "cd $DIRNAME && git config --global user.name 'Github Pipeline' && git config --global user.email 'quentin.desmettre@epitech.eu'"
-          ssh staging "cd $DIRNAME && (git remote rm epiRepo || true)"
-          ssh staging "cd $DIRNAME && git remote add epiRepo '__REMOTE_URL__'"
-          ssh staging "cd $DIRNAME && (git fetch --unshallow || true) && git fetch --all && git fetch epiRepo && git fetch epiRepo $BRANCH"
-          ssh staging "cd $DIRNAME && git push epiRepo $BRANCH -f"
+        uses: pixta-dev/repository-mirroring-action@v1
+        with:
+          target_repo_url:
+            ${{ env.MIRROR_URL }}
+          ssh_private_key:
+            ${{ secrets.SSH_PRIVATE_KEY }}
